### ISSUE TITLE
对lua模块支持太差了

### ISSUE THREAD

**Issue by liwenson** [fangpeishi/ngxfmt#4]
对于 rewrite_by_lua 这种支持不好，格式化的配置都乱了，之前的版本好像不支持lua的格式化，但是不会去处理，不会弄乱配置

**Comment by fangpeishi** [comment]
你好，基本没怎么变过，可以查询commit 历史。可否给下测试文本？

**Comment by liwenson** [comment]
由于公司人员比较混乱，配置改的稀烂，之前用大佬的脚本格式化一次，效果很不错，这次想在格式化一次，发现lua 块的代码 格式化错乱了，https://raw.githubusercontent.com/liwenson/liwenson.github.io/master/abc.cn.conf,就是这种lua 模块比较多的配置

**Comment by fangpeishi** [comment]
你好，暂时没有精力支持Lua 的解析，也因为目前的处理过程，我没法直接忽略lua 模块的代码直接照搬。可以把lua 都改写成*_by_lua_file，顺便做一次整理工作。
另外冒昧，贵司现在的配置实在是非常乱，难以维护，出现问题也难以debug。

**Comment by liwenson** [comment]
麻烦大佬了，我改成*_by_lua_file 试试
